project_id = "ernuscqjcluitrtyilnc"

[functions.sync-completions]
verify_jwt = false

[functions.discord-notify]
verify_jwt = false

[functions.admin-notify]
verify_jwt = false

[functions.resync-extra-levels]
verify_jwt = false

[functions.sync-extra-completions]
verify_jwt = false

[functions.resync-main-levels]
verify_jwt = false

[functions.resync-future-levels]
verify_jwt = false

[functions.hardfix-resync]
verify_jwt = false

[functions.hts-cup-check]
verify_jwt = false

[functions.discord-bot]
verify_jwt = false
